### ISSUE TITLE
ポップアップ時のテキストエリアへのフォーカス

### ISSUE THREAD

**Issue by wakin-** [noraworld/fastoot#14]
メニューボタンやショートカットキーでポップアップを表示した後、テキストエリアをマウスでクリックするかタブを1回押す必要があります。

ポップアップ時にテキストエリアにフォーカスを当たるようにできますでしょうか？

**Comment by noraworld** [comment]
Issues and pull requests are only accepted in English.

If other Japanese people see this issue, please keep in mind.
